core/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings.base import DEBUG

from .settings import base
from django.contrib.staticfiles.urls import static

admin.site.site_header = base.SITE_NAME+'管理サイト'
admin.site.site_title = base.SITE_NAME+'管理サイト'

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('accounts.urls')),
  path('course/', include('course.urls')),
  path('chapter/', include('chapter.urls')),
  path('lesson/', include('lesson.urls')),
  path('query/', include('query.urls')),
  path('notification/', include('notification.urls')),
  path('situation/', include('situation.urls')),
  path('', include('home.urls')),
  path('', include('user_sessions.urls', 'user_sessions')),
]
urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

if DEBUG:
  import debug_toolbar
  urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

lesson/urls.py
from django.urls import path
from .views import Index, HistoryView

app_name = 'lesson'


urlpatterns = [
  path('<int:pk>', Index.as_view(), name='index'),
  path('history/<int:pk>', HistoryView.as_view(), name='history'),
]

situation/urls.py
from django.urls import path
from .views import IndexView, LessonIndex

app_name = 'situation'

urlpatterns = [
  path('', IndexView.as_view(), name='index'),
  path('lesson/', LessonIndex.as_view(), name='lesson_index'),

]

lesson/models.py
from django.db import models
from chapter.models import ElmsChapter
from accounts.models import CustomUser
from simple_history.models import HistoricalRecords

def lesson_image_file_path(instance, filename):
  return f'images/lesson/uploads/{filename}'

class ElmsLesson(models.Model):
  title = models.CharField(verbose_name='題目', max_length=200)
  type = models.CharField(verbose_name='種類', max_length=20)
  content = models.TextField(verbose_name='内容', blank=True, null=True)
  timelimit = models.IntegerField(verbose_name='学習時間', blank=True, null=True)
  pass_rate = models.IntegerField(verbose_name='合格点', blank=True, null=True)
  created = models.DateTimeField(verbose_name='生成日時', auto_now_add=True)
  modified = models.DateTimeField(verbose_name='更新日時', auto_now=True)
  deleted = models.DateTimeField(verbose_name='削除日時', blank=True, null=True)
  memo = models.TextField(verbose_name='備考', blank=True, null=True)
  elms_lesson_chapter = models.ForeignKey(ElmsChapter, on_delete=models.CASCADE, related_name='lesson_chapter', verbose_name='単元', )
  elms_lesson_user = models.ManyToManyField(CustomUser, through='ElmsLessonUserShip')
  image = models.ImageField(verbose_name='資料画像', upload_to=lesson_image_file_path, default="images/dummy/dummy_image.jpg")
  history = HistoricalRecords()

  def __str__(self):
    return self.title

  class Meta:
    db_table = 'elms_lesson'
    verbose_name = '講義情報'
    verbose_name_plural = '講義情報'

class ElmsLessonUserShip(models.Model):
  COMPREHENSION_TYPES = (
    ('', '--理解度を選んでください--'),
    (5, 'よく理解できた'),
    (4, 'やや理解できた'),
    (3, 'どちらとも言えない'),
    (2, 'あまり理解できなかった'),
    (1, '全く理解できなかった'),
  )

  lesson = models.ForeignKey(ElmsLesson, on_delete=models.CASCADE)
  custom_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
  comprehension = models.IntegerField(verbose_name='理解度', choices=COMPREHENSION_TYPES, blank=True, null=True)
  created = models.DateTimeField(verbose_name='生成日時', auto_now_add=True)
  modified = models.DateTimeField(verbose_name='更新日時', auto_now=True)
  deleted = models.DateTimeField(verbose_name='削除日時', blank=True, null=True)
  history = HistoricalRecords()

  def __str__(self):
    return self.lesson.title

  class Meta:
    db_table = 'elms_lesson_user_ship'
    verbose_name = '講義理解度'
    verbose_name_plural = '講義理解度'

situation/models.py
from django.db import models

# Create your models here.

situation/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic import TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from course.models import ElmsCourse
from chapter.models import ElmsChapter
from lesson.models import ElmsLesson, ElmsLessonUserShip
from core.utilities import getNotifications

class IndexView(LoginRequiredMixin, TemplateView):
	template_name = 'situation/index.html'


class LessonIndex(LoginRequiredMixin, ListView):
  def get(self, request, *args, **kwargs):
    context = {}
    context['courses'] = ElmsCourse.objects.filter(deleted__isnull=True)
    context['chapters'] = ElmsChapter.objects.filter(deleted__isnull=True)
    context['lessons'] = ElmsLesson.objects.filter(deleted__isnull=True)
    context['lesson_users'] = ElmsLessonUserShip.objects.filter(deleted__isnull=True, custom_user=self.request.user.pk)
    context['notifications'] = getNotifications()
    return render(request, 'situation/lesson_index.html', context)

templates/situation/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %} {{ SITE_NAME }} Situation{% endblock %}
{% block bootstrap5_extra_head %}{% endblock %}
{% block content %}
<div class="row g-5">
  <div class="col-md-8">
    <h3 class="pb-4 mb-4 fst border-bottom">{{ SITE_NAME }} Situation</h3>
    <div class="row h-100">
      <div class="col-6"><a href="{% url 'situation:lesson_index' %}" class="btn btn-outline-primary w-100 h-100 d-flex align-items-center justify-content-center" size="lg">受講状況</a></div>
      <div class="col-6"><a href="{% url 'situation:examination_index' %}" class="btn btn-outline-success w-100 h-100 d-flex align-items-center justify-content-center" size="lg">受験状況</a></div>
    </div>
    <hr />
  </div>
  <div class="col-md-4">
    {% include 'right_sidebar.html' %}
  </div>
</div>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

templates/situation/lesson_index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block bootstrap5_extra_head %}{% endblock %}
{% block bootstrap5_title %}{{ SITE_NAME }} | 受講状況{% endblock %}
{% block content %}
<h5 class="pb-4 mb-4 fst border-bottom">{{ SITE_NAME }} 受講状況</h5>
{% for course in courses %}
  <blockquote class="blockquote">
    <p>第 {{ forloop.counter }} 章　{{ course.title }}</p>
  </blockquote>
  <ol>
    {% for chapter in chapters %}
      {%  if course.id == chapter.elms_chapter_course_id %}
        <li class="mt-3 mb-2">{{ chapter.chapter_title }}</li>
        {% for lesson in lessons %}
          {%  if chapter.id == lesson.elms_lesson_chapter_id %}
            <div class="row py-1">
              <div class="col-6"> <a href="{% url 'lesson:index' lesson.pk %}" class="text-decoration-none">{{ lesson.title }}</a></div>
              {% for lesson_user in lesson_users %}
                {% if lesson_user.lesson_id == lesson.pk and lesson_user.comprehension %}
                  <div class="col-4">{{ lesson_user.get_comprehension_display }}</div>
                  <div class="col">{{ lesson_user.created|date:"Y-m-d" }}</div>
                {% endif %}
              {% endfor %}
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
  </ol>
{% endfor %}
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}